/** 
DDDDDDDDDDDDDDDDDEDDDDDDDDEEHDPY6SYZPPPPPPPPPPPZYYYZZZPZZZZZZZZZZZZZYZYZZZZZZZPPPPPPZZPZZZYZYYZZZZZZPPPPPPPPZZZZZZZZPPPDPPZZPPPPPPPPPPPPPPDDPDPZZPPPPDDDPPPPDPPPPDPEDEEEEDDDDDDDDDDDEDDDDDEDEPPYYPZPPPPH
DDDDDDDDDDDDDDDDDDDDDDEEHDPZZZZZZPPPPZZZZZZZPPZZPPPPZZZZZPPPZZYZPPPPZZPPZZPPPPZPZZZZZZPPDDPPPPZZPPPPZZZZZZPPPPDDPZPPPPPPZZPPPZZZZZZZZZZPZPPPPPZYZZPPPZZZPPPPPPPPPPPPPDDEEEEEEDDDDDDEEDEEEEEPDEEHHEEHHHEE
DPPDDDDDDDDDDDDDDDDEHEHPPZZZZZPPPDPPPPPPPZZZZZYZZZZZZZZZPZZZYZZZPPZZYZPPPPPPPPYYZZZZYZZZZZPPZPZZDPPPZZPPPPZZZZPPZZPPPPZZZZPPPZZZZPPZZZZPPPPPZPPPDDPPPPPZPPPPPPPPDDDDDDDDDDDDDEDDDEDDDEEDDDDPPDDDEEEDDEED
EDDDDDDDDDDDDDDDEDEDDZZYYZPPPPPZZZZZPPZZZPPPZZPZZZZZPPPPPPZPPPPZZZPPPPZZPZZZZZPPPPDPPPYYYYPPZPZZDDZZZZPPZPZZZZZZPZPPZZZPPPZZPPPPPPPPPPZPZZZPPPPZZZZPPPPPPPPPPPPPPDPPPPPDPDDDDEEDDDDEEPPDDDDDDEEDEPDHNDPH
DDDEEDDDDDDPPPDEHEEZZYYPPPZZZZPZZZZZPZPZZPPPDPZZPPPZYZZZPPPZSYZZPPZPDPYZZZZZZZZPYYPPPPPDPPZZPPZZZZYYPZPDZPDDZZPPPZZZZPPDZZZZZZPDDPPZPPZZYYPPPPZYZZPPPDPDPPPPPZZPZPPPDDDPPDDEDDDEEHHPPDDEDEEDEEEPDZPSP2sH
DDEDDEEDDPPDEEHZZSSPDZZZZPPPPPPZPZZZPPPZYYZZZZZZZZPPZZZYSYZZPPDDDDYYYYSYYYZYYYPPYZZYZYPPYYZZPZPPZPPPDDZZZZPPZZZZZZPPPPZZZZZPPPYYZZPPZZPDPPZYZPPPPPPDPYZZZPPZZZPDPZZYZPPPPPPPPPPHHZZPPEEEEDDDEDDDDEN5Y62N
DDEDDDEDDDEEEPPZZZZPDZZZZZZZZZPZPPPPPZZZZZZZZZZZZZZZZZPPPPPZYYYYYYYZPPDDYZZZPPPPPZZZPZPPZZPPZZPPPPZZZYYYYYYYZZPPPPPPPPZZPPPPZZPZZZZZZZPPPPPPPPZZZZZPPPPPPPPPDPPDDDDPPPZPPDDPPEDPPYYHEEEEDEDDEDDDDENZDHED
DDEEEDDDEDEZPZZZPDDPPPPPPZPZPZZZZZZZZZPZZZZZZZPPPZYYYYYYSYYYZZPPPPZZZZYYYYZYPZZZZPZZPPPZPPPPZZYYYYZYPPPPPPPZPPYZPPZPZZPPPPZPYYZPZZZPPPZZZYZPPPZZPPPDPPPPPDPZZZPDDPPZPPPPPDDPPEDZPDPEDZZDDEEEEDEDEPDDHPPZ
DDDDDDEDHZPZZPDZZZZPPPPPPZZZZZZZZYYZZZZZYZPPPPYYSSSYZZPZZZPZPZZZZPPPPPYZPZZZZYZZZZPZPZZYPPZZZZPPZZZZPZZZPPPPDDYYYZPDZZPPPZZZPPZZZPPPZYZZZPZYZPPPPPPPZPZPZYZPPPPPPPPPPPPPPPPPPPPPDDPPPPPDPEEEEDDPDYP6YZYE
DDDEHEHZPYYPPZZPPZZZZPPZZPPPPPZZYZYZPZZPPZZYYSSYZPPPZZYYZYSYZZPPZYYYZZPPYYYYPPZZZZPZYZZYZZYZPPPPZZZZPZZZYYYYPPPDZYZPZZZPPZZYPPPPPPPPPDDDPZPZPPPPPPPPPPPDPZPDPZZZZPZPPPPZPPPDPPPDPDDDDDDDPDDDDEDEHENZPDPH
DEEEHZPYZPPZZZPZPZZPPZPZZZZZPZZZZPPPPZYYYS6SSZPPZZZZZZZPPPDDPPYZZZPZZZZZPZZZZZZZZZPPZZZZPPPPPZZZZZYYYYPPPPYYZYZPZZZYZZYYZZPPPPPPPPZZZZZPZZPPPPPZZZZPPZZPPZPPPDPPPPPDDDPPPPPDDPPDPDDDDPDDPDDDPDDDDDNYZEPD
HDHYZYYPPPPPPPDZZZZPZZPZZZZYYPPDDZYYYYYZZZPPPPZZYZZZPPZZZZPZZZYYYYZZZZZZPPPPYZZZZZPPZZZZPPYZYYZZPPPPZZZZPPZZZZZZZZPPPPZZZZPPZYZZZZZPPPPPZYZZZZZZPDPDPPPPZPZYZPPPPPPPPPPPPPPDDPPPPDDPDDDPPPPHEEDEEPHSYHDE
EZPYYPPPPPPDDPPZZZZZZPPZZZYPDZYYSYZZPPPPZZZZZZPPPZZZZZYYZYYZZPPPPZZZPZZZZZPPYZZZZZPPZZZZZPYYZZDDYYPPPPYSZZZZZPZPZYPPZZPPPPZZPPPPPPPZZZYZZZZZZPZYZPZPPZPDPDPZZPPPPPPZZZZPPZZPPPPPPDPDDDDPPPPDDEDEEDH6SPYH
PYZPPPPPPPPZPZPPPPPYYYZZZPZYYZZZZZYYYYYYZZPPPPZYYZZPDPPPPPDPYYYZPPPPYYZZZZZZYYZZPPZZPPPPZZZZPZZPYYZZZZZYPPZZPPZZYYYYYYYYZZPPPZZYYYYZPPPPZYZPPPPZPPPDPZZPPPPPPDPPPPPPPPPPPZZPPPPPPPZPPPPDPDDPPDPEDENZDZYH
PPPDDPPPPPPZZZZZZZYZPZYYYYYZZZYS6YZPDPZZZPPPZZPPDPYZYZZZZZZZZZPPZZPPDDZPPPPZPZPPZZYYYZZZZZPPZZZZZZZZPPYYYZZPPPYYYSZZZPPPZZPZPPPPPPPPZZZZPPPPPZZZZPZPZZZZZPPPPPPPPPPDPPPZZPPPPPPPPPPPPPZDPDDPPEDHEDEPEYZN
PPPPPPPZZZZPPPDZZPPDDZYPPPPZYYYPPPPPZZZZZZZYYZPPPZZZZZZZYYZZZPPPYYYYZZPZZZZZPPZZZZZZZZZZZZZZPPPPYZYYZZPPPPZZYZYYPPPPZZPPPPZZYYZZZPPPZZYYYYZPZYZPPPPZZPZYYZZPZZZPPPPPPPPPPDDPPPPPPPPDDDDDDDDPPPPDDDDHNYP6
PZZYYZZZZPPPPPPZYPPZZSSZPPPPZPPPZZZZZZZZZZZZZZZZZPDPPZZZZZYYSYZZZZZZYYZZZZZZZZZZZZZZZZZZZZYYZYZZYZZZPPZZZPZZPPYYYSZZZZYZYZZZZZZYYYZZPPPPZZPPPZZZZZZPPDPPPPZZZZZPPPPZZPPDPPPPPPPPPPPPPZPPPDDDPDDPPPZEHPN6
PZPPPPPPPPPZPYZYYYZZPPPZYYSPPPZYYYZYYZPZZYYYZYSYZZZYYZZPPPZPZPPPZZZZZZZZZZYYYYZPYYYYYYYYPPZZZYZZZPZZZZYZYYYSPPZZYYYYZPPPZZYYPPPPPZZZZZPPYYYZZZZPPPPPZYZDPPPPPPPPPPPPPZZPPPPDDPPPPPPDDPPPPDDDPEDPPHEHHENZ
PZZPPPPZPPPPPZZZZZPZZZZZZYYZYYZZPPZZZZPZYZZZPZZPZZZZZZZZZZPZYYYYZZZZZZZZZPZZPZZZSYZZPPDPPPYYPZPPYZYYZZYYYYYYPPZPYYYYYYYZZZZYYZYYYZYZYSZPZZZYZZZYYYZPZYZZZPPZPPPZZZZPPPPPPPPPPZPPPPPPPPPDDPPPZPPDPPPZDZE6
PYYZZPDPPZZZZZZZPZZZZPPPDPZPDPZZYZZZZYYYSYZZPZSYZZZZZPPZYZZZYZZZZZPPZZZZPZYYYYPPZZYYSSYSZZYZZZPPYYZZZZYYZZPZZZZZZZYYYYYYYYPPPPZZZPPPYYYYYYYZZPZZZZYZPPPZZZZPZPZPPZZPPDPYZPZPPPPPPZZPPDDDPPPPPDDDDPDPE6YS
ZPPDDPPZZYYYYZPZZZZZZPPZPYYPDPZYYZPZZPPPPZZZZYYZZZZZYYZZZPPPPPZZZZZZYZYYYYYYYYZZPPPPYYYYPPYYYYSSYZZZZZZZZZZPYYZYPPPPPPPPYYZYYYYSSSYZZPZZZPZZZZZYZPPPZSYZZPZZZZZPPZZZPDPYZPPPPPPDPPPEDZZPPEEPPDPDDEHYP25Y
ZPPZZYYYYZZZZPPYYPPPPZZYZZPYSSYZPZZYYZZPPPYZPZYPPPPZZZZZZZPPZPZZPPZZPZYYYZPPYZYYYYYYZZPPYZSSPZZYZZSYYSYYYYZYYYZPPPYYYYYZYYYYZPPPZZZYYYYYZZYYYZZYZPPPZYZZZPPPZPPPPPPZZPPPPDPYZYZPPPPPPPPZZPPEDPPDDZPYZHHH
PPDYZYYPPPPZZPPPZPPPPZZZYZZZZZZYYYYZZZYYYYZPPZYZZZZZPPPPPPZZSYYYPZYZPPPPYYZYZZYYYYZZYYYYZPZZZYPZZPSSPZPZZZZYZZYYYYYYYSYYYYYYZZPPZZYYPPZZYYZZZZZZZZZZPPPZZYZPPPPPPPPZZPPPPPPPPZZPPPPZZDPPPYYPZEDPPZPDPPPS
ZPPZZZZPDPPZYZPZZZZZZZZZPPPZPZZPPPZPZZZZPZZZZZPPPZZPPPZZZZYYYZYYZZSYZYYYZZZZZZZPPPZZYYPPYZ55YSZZZPSYZZSSYYZYPPYZYYZPZZYYYYYYZZZZZPZYY6SYYYZZZYZZZPPZZPPPPYZZZZZPZZZYZPPPZZZDPPPPZPPPPPPDDPPZYDPEEPPPZEEP
PPPYYPPZZZZDDDPPPPPZZYYZZZZPDDDZZYYZPPPPDPZZZZPPPZPZZZYYZZZZDPZZZZPPZZZZZZZZZZZZ6SSSYYYZZZZZPZZZZZZZYYYYPZPPZZSYSSYZZZZYYZYYZZYYYZYYYYZPZYYYYZYYYYYZZZZZZZZZZZZZZZZZZPPPPPPPPPPPPPPDDPPZZPPDDPZPPPPDPHED
ZZZPPDDZZYYZZYZYYPPPPZZZZZZYYYYZPZZZZYYYYYPPPPZZZZYYYYYYPPZZYY66SSZZZZPPYYZZPPZZZZDPYY66YYZZZZSY66YYSSYYSSYYZZZPYYSSYYYYPPZZYYZPYSYZPDPPZZYZYYYYZPZZYYYYYZZPPPPPZPPPPPPPPPPPPPPPPPPZZPPDPPPDDDDDDDDPZEDE
ZDDZYZZZPZZZZZZZZZZZZZZPZZZZZYYPPPPPPPPPPPPZYYSYZZZZPPPZYYZZPZZPDPPZYYYYZZZYYZYZPPDPPPPPPPYYYYZPYYDDSYPPYYSSYYZZYYZZYYYYZZZZYSYZYYYYYY66SSYPYYYYYZYZZZZZZPZYYYZPZZZZZPZYZZZPZPPYYZZPPZZDPDDZZDPPPPPDPHDD
ZZZYZZZPPZZPPPPPPPPPPZZZZZPPDPZZZZZZPPZZZYYYYZPPPZZZZZZPPDDDEEEEPDEEHNNNNNNNNNHEPZDDDDDDEEDDDDEDPZZZYZZPZZPPYYYYZZYYYZYSYYSYYSZPZZZYZZZZYSYZPDZYZZZZYYZPZZZZZPPPPPPZZPPZZZZPPZZZZPPPPZZZZDDZZPYDPDDPZHDE
PZYPPPZDPPPPPZZZPPPDDDDPPPPZYPPPPDDPZZZPPPZZZPDDEHHNNNNNNNNNNNNNNNHHEEDDPPZZPPDENNNNNNNNNNNNNNNNNNNNNEPPYSZZYZZZPZPZYYS6ZPZZYSZPZZYYYYZPZZYYYSYYYPZPZYZYYPZYYZYYYZZPZZZPPZZPPZZPZPPPPPPPPZZPPPZDDDEZZPZE
PPPDDPZPPPPPDPPPDZZPPZZZZZPPPPZZZS5YPZPYSZDNNNNNNNHEZS2c::                                      5sZSNNNNNNNNHDPYS6YZZPPZZYZPZPYYYYYZYYYYYZZYYYZPPPZZYYYYYPZZZZZZPPZDPDPZZZZZZPPPPDPDDYYDPZZZZDPDPDDZZDPE
YPZPPYYPPPZDDPPPPZZZZZZDDDDPPYYPEPYDHHNNNNNE62;                                                           52NNNNNNNNNEPYYYZZDEPZYSYYYZZPYSYZZZYYYYYPZYZYZZZYYZYYYYYPZZZYYPPZZPPZZZYPPYZDPDDYYEPEDZZDPEDP
ZPPPPPPPPZZZZYYZZPPPPZZYYPDEHHNNNNNNH6c                                                                           26NNNNNNNDPYZZDHDPPZPPZYYYYYYYZZPPPZPZZZZYZEDPPZZPPPPDDPPZZPPZZZZPPPPZZPPZZPYDDDDPPPPP
PPPPPPPZZPDPPDDPZZZPDENHNHHEHYS:        ;scs...:ss;;;;::..                                                              :sPPNNNNNHDPYSZZZPPZZZZZZZZZYYYYYZYYYZZPPZZYYYZZZPPPPPPPPDPDDZPPPDPPPZYDPDDPDPPD
YZYPPZZPPPDZZYYZPDHNNEH66:         6P5sc2s;c5YEZ6PHEPPPYcs:.                                                                  :cZPNNNNDZYYZPDDPZZZZZZZZZZPPZYYYYZPPPZPZZZYYPPZZPPPPPPZPZZPPPPPZZYDPDDPDP
YPPPPDDDDZYYZPHNNZZ::              :cc2c:c5SYSY65;        :;c262 .                                                                  6ENNNNDY66YYZZYYYZZZZZZYZPPZZYZPPDPZPZPDPPZPPPPPPPPPPDPPPPPDPEPDDPPP
PPPPZZZSYYPNNNN22     .  . s;c225S665c2562s;:s2;.:;ss26PNNNHPDNNEEYYc2;s                                                                2PNNNNDSYZPPPPZYYYYYZPPPZZZZZPZDPZZZZZZZYPPPPZZDPDDZPZZPPPZHEPPD
ZYYPPZPHNNNYD     : .      scSPYY5c262266S6522cZNDZPDPZ6255cs   26ZY2;                                                                      ;HNNNHDPZZZZZZZZYSSZZPZZZZZPPPPZZZZPPPPPPPPPPDDZZDDPDZYDPEDP
DPDDHNNZE :   .:;....::::. scYP2;SPSScc    2D6;sssss::s.    Y5s;   sEHNNSS ::;                                                                 .YNNNHEPPZPZYYYYZZPPPZZZZZZZPPPPPPPZZZPPPPDDDDDDPPPPDZHEP
PENEN:5    .s:;:.;;::;;5652c;:;::::.;             .. sEPPDPPDPDD66    ss26YY6525 .                                                                 5DNNNEDZYZPPPPZZZZZZPZPPZZPZPPPPPZDDZZPPPDPPPDZPYSHDP
NYD;5 . .;s:;    ::ss.   :s;;  .:   ;                   ;;;: .2s :..      .:2cDZ s:;;;                                                         .      .DENNNPYYZZZZZZZZZZPPZZZYZYDPPPDPPPDDZPPPDEPDYSEPE
Z : ::c;s:s.;      .::;:;..                                   s;csc2;s226s      2c  ss                                                             .     ;6NNNEYYZZZZZZZZZZZZPPPPPPZZZZPPDDZZPPDDPDZZDZH
;:2.; ::s.: ...::. ..                                         ::c2YSc252;cNHDZ  S666  c2                                                        .;:....:     DENNPYYYZYZZPPPPPPPPZZZZPPPPPZPPZZPPPPPPPYH
s:s:s:s   .    .:..  .:                                             .   ;.  YY55: SS      ::                                                           :::.    2YNNNEPZZZZZPPPZZZZZZZPPZZPZDDPPPPPDPPZYE
2:;;c:s :.:    ..  .......... .                                                 :.52c5      ;;                                                     .:s:;: :c;:     NDNHEPYZZZZZZZPPZZPZPPPPDPPZDPPPZPZYD
s:s:s   .          .    . .   .                                                      .                                                               ::;:  s.  .     DZNNDPYYZZPPZZZZZZDPPZYYDPDDPPPDZZP
s:s :  .:... .         .:..                                                                                                                               .2s2s .;;:   ZSNHPZDPYYPPPPPPPZPPPPPZPPPPDEZPP
; : :.:.:      ..  . ::. .:..                                                                                                                            .:2csc5cs;:::   S6NNPZZZPZZZZZDPZZZYDPPPPPDDZPP
s.:        :;    :.s:cs2222csssc5c2ss;:                                                                                                                        ;;2s;:.:5;  2cNEPZPZDDZZPZDDPPDDDDPPPPZPP
: .      ::.:      :.s:cs2c66YYSS2c:::;5Y6c.                                                                                                             c:.   .   ::::;;c;. EYHDPPZZYYPZEDZPYYDPZZPPPDZ
:::.::;  :;        .   s;cs56PENNNNNNNNE6DENNNNDZDDHHYs    .ss;;                                                                              ;2: .;cS2 :ss5c   .62;;s:  .:2ss;HZHDZPZPPZPZPPPZPZDDPPPDP
s.:;;;;  .:  ..... ..;.22SZS6cs::;:5Y:     6NEPHN5  ;6NNSYSYY5 :scss                                                                        .s:.s52c5YS52s;scsc:;5s;cPY65:;cs2;s:NDHEZZZZPPPPEDDDPDPPPPP
:    :.s2 . .. ..::::. ::            s6622:YNDPDNPc56SHNNNNN6ZPS2s .22::                                                                  .;:::;c556c:;26ZSccscs2Z652scYY66;cY66c6cHPDPDDDDPPZYDDZZPPDEZ
s::  sc.: .:.::::;;;s::..              ;2YZPEHNHDNNNNNDDPc     :NNEPsssc.:                                                                   :sccc25YDDHDYYS652s2DPEPSS66YY25c2DP2cDYHDPZZZDDDPDPPPDPDDP
:.:ss;;  ..:::::::.::;;;;;;:.::::.               .:cEPHS .          Y665:s ;                                                          .:;s26c ::;;;:cS2::.:;cSYPZZSDPEDZZDPZZSSYYSSY6DZEDDDZZPPPPDDDDPDP
 ..;;    ::..:;..                 .                    :c2c2556562: :;HPYSs5                                                          .          .::;s;.s2255Y66cssY666YSDZDDDPYYSSY6ZYEPDDZPDDDPPPDDPPP
;:;::::::;s                                                     .:cs:   6SHHcS                                                                         :   ::2255ZSZYZ665PZDPSYYY55ZYDZZYEDPDZZDPPPPPPDP
c    .:.:                                                                 ccYP                                                                             :    .P6;sZYNP65ZYPDHDZYZYZZDPHEPPYYZYDDDDDEZ
: .::::   .                                                                                                                   .:::;;;s::;;:::.                         s:52PY2252HPHPYYS6PZDDPPEDDDPPPDZ
;.::::s                                                           ....::s; .                                              ::ss;:..::                                   : 6s::::s:SsDYHEPYYSDDPPPPZZDDPDP
; .                                                                                                           ...:  . :;ss;:::::.                                    .   6c;scsc;YcD665PZDPPPDDPPPZDDPDP
; ..:                                                                             ..                      :.: .. :  ::sc .           ...                             ..2s6c  ::2;2:HPDZEZDZDPDPDDPPDDPDP
.   :                                                                          .                      ... : s;2c;s  .. .         :s2: :sscs:c26Z62s.               ;.:.;...::522cY2P6Y5EZHDPDDDDDPPEEPPD
.   :                                                                                 ..    ....    . .   : c;2c55c2::;2    . ZNNNHHHHZS65           sss:            :   :.2ss;;.; Y562EYNEPPZYEDPPDDPPE
:.; .                                                                             .             ..  . . ;:;.;.s:22c2;s:c    NNEDc:        5NNNHES:       s265c:        2s;:2sss2sS2Y5Y5PSDPHDPZEDPPEEPPE
;.:                                                                                             .     ;.s:s:;.s:2c56s2.;  c.2c :::2555.   .DENEYYcENHYS;:    :cS62s    ::s;2c2c2sY662S6ZYS6PSPSHEPPEEDDD
. : :                                                                       :.::                  ::  : : ;.s;s;s:25s5.;..: 25      :;25DPHNPY2:: 6NHDHHNNNNP;: ;56Y62c :;;cscs5265SSY6662cP6HPHDEDDDDDE
.   .                                                                     ....                    ..    . s:2scs:.c2c5:s.:. ss5Y;.        .2SDNNNNND6sYNNNNZNNHs.  25YSss:;2s2c52656666YS62P5ESHPEEDDDDE
 ::.:                                                                                           s:::  . c;;.s:55sscc25s2      :;5Zcs           s6DHNNNHS      2NNY6.:;cYY;css5cS6SS26225262P5EYHPHEDDEED
; ..:                                                           2c225552::                        : s;: s.s;; 5225:.scc6 :       .s5;:             :2P6cc :    ZPNNHD256S;2scS6PZYYs2ss2s5sHYDSHPHEDDEED
:                                                         .:;s22ssssssscscsccc .   .          . : ;.;:;:: csc;2s56sssss5:s :        .;  .:::           c6SPHEDYcs22NHHHZP2622S6SS6Sc2cc62Y5D6DSNDHEEEDDD
:.:                                                     ;;sss;:: .:.......   . .                . ;:;:;.;.cs2s2c2225sss2;2:s         ...   .::::.          ::ssss5cZ6ZZ6YYPPPPZ25c2c2525cY2P6D6HDDDDDDDE
:.:                                                   cs;::.                .                         : 2ss:c;222cc2c5scsc ;                 :;c;:;c;:::::.  .;52S6DZEP2666scsssscc22622sY5D6HYNEEDEEDDD
;   .                                                 :.                                              : s:s.2s2c2c6656:;;cs5                   .:::::sscc222css22622cs2YY65 : :s;52522cS5Z6P5HYHDDDEDEED
:.:.:                                               c:.                                                 . s 2;52522c56sc:;;c:;                    .:::...;;sscs2scscssc2cc222sss;522252625sD6NPHEEEDDEED
:.:                                                 s:                                                      5;5c2c5566SP ..;:s               :     .. .:...::cscscc222s;sss2222cc2ccs6262S2HSNDEEDDDDDED
. :                                                 ;.                                                      : 5s5c55csZEc5   : .            .:.      .:;:::::;:sscscs2252cc222555655265Z6P6HYHDEEDDEEDDD
::; :                                                 s:      :;S666Ss                                        ; 6c652sc;PN:;   :              .:..   .  .::;:::::;:cs2222226552cs522c5cS2Z5HZDPEEDDEEDDD
:   .                                                  .c:          .2NNNE                                      : ssss5c22DN.                  .:;:.     ::;;;;sscscscscc6555256566655cZ6DSNEEEEEDDDDDDE
s .                                                       ss;:..       .NN6Z                                        :.: 2;25YN.                   :s;::     .;:;:;:;;2c2c526522522c62PSS2HZNEDDDDEDEEDDD
..:.:                                                                        ..                                         c;5sYEc2             :     ::;;;:.. .::;:;:sscs2252S6225565Y6PSP6NDHEDEEEDDDDDDD
   :;                                                                         ;:;:                                      : 5;ZP6D.           .s::.   .::s;::   .cscs2scs2c5266SSS665Y5Y5HPNEDDDDEDDEDDEDD
:.:   :                                                             ;:          ;;::                                    . : 25SN:               .::..  ....::.::;s;cscs2262626665Y6Z6EZHDEDDDDDDDDDEEDDD
::;   .      .:                     ;           .                                 ..::        :.2cYSZYZSDZ6522 :        : c.6YcY                  .:;;:;::;css: .:.s;2c2c52S6S665Y6P6NEHEEDDDDDDDDDDDDDD
..:        ::.. .                .;:;:.               ..    .       c252ZSYS  .:     :sc;;52ss:.        22EDNNNN6Scs    : s.ENc:                       ::;::;cscs;;2s522c62Y66662S2HZNEDDDDDDEEEEEEEEEEE
:    ::::;;..  .:  ..:.    s56SYZS6: s556c:.  :: s6YNEPY26YYPS26HHNN66c2NDHNNNHN6Yc2 .                             .::s;2sDD5S                         ::::::ss2css2c2c2c65ZSSS65DSNEHEDDDDEDDDDDDDDDDDD
...;::.:;:: ..:        :.6PPDHNSs25ZEY2s::;2ZS52;5YYP6.::;c26S66Y2 : .  2s;;ss.;;cDE ;    . s:::ScZZ : .  ;:226Y2cs;2cSSY652.; :                    ...;:::::ss2c2ccc65S6S6ZYYYS5HZNEDDDDDDDDDEDDDDDDDDD
:  ...:..  .:        . SYYZSY2cs;2S: ;;ssc5YD5 ::;c   26EDZ6c.  DZs6c6D6 :22:::;;;.: 2:5; 6:5s::  NNcZ .:;.:::;sss2ccc;:. .:;2:;                   :.  ..s;::ss2c52scS6S6Y6YSYSZSNDEDDDDDEDDDDDEDDDDEDDD
 ::56  .:::      . 65NNPYYPs:  :6sc    cHPPs   s256SZPHY:: ;DPPPHE56 .66NHssEDDP252SDN    PsP6PE; Z2ZH ..;                ::;;:s                        .;:::s:;;526652Y6PYS6S6DYNEEEDDDDDDDDDDDDDDDDDDD
s.   .:    25;s: 2;6266;;s5  .:                     c:      ;;2;      :   . . ::5SZP    : 5 NDPZY5NDNNHNYZ5Z ;.s        . :.scs2:;                     . ..;;sc6565Y622S6S656HDNEHEDDDDDDDDDDDDDDDDDDDDD
:ss...:    ;;.;  56S55c25                                          .;.    2sc;6c        s Yc2s  ES62s.52DHZHcS : .  :;::::::;;:s..                   :.....::ss6565S6SSZYS6YYNEEDDDEDDDDDDDDDDDDDDDDDDDD
 ssc2::..:::.:;       .c5SP6cc2.                                            . 6266:;22    ;.  s NZs;6:NHNNENDNZPSP;s.:::;;;::::;:;                     ;:::;;22S5S6YS66S6YYHDHEEDDDDDDDDDDDDEDDEDDDDDDDD
 ;::;:::::;....s5sss;s;:   ::YDDD2:        .::.                                 ;;Y6Y6c6        c.: 6 HH2s6622ZPPH6Z:: : .::.:. .: :              ....:s;;;ss2c65YSS666S6DZNEEDEEDDEDDDDDDDDDDDEDDDDDDDD
:;;  ..::::  :: :  ..   .:;    ;5DNHEPZYS65222222csssss;..                          2cSZ26s;S6S5s:2.NP65c;S5ZYPZDH256P56. :c;s: :;;c.             .;.  ..s;cs22YSYS66YSYSNDHEDEEEDDDDDDDDDDDDDDEDDDDDDDD
 ::......  :.6Yc5          :::.  :s262c5S2ssssc2222222cs;s2cs:   .                            :.:.c.6;222:PSHDDZYYPH6S5Y25:c    :;;s:;        .;;;:::.:::ss65SSZY66YSS6EPNEEDDDEEDDEEDDDDDDEEDDEDDDDDDDD
:;;;;::..:.:: .:c                    .:.:::.           .:::s55Z6 ;::              .   :.::            522.P65s2sPYZDSP226Z:2  ;;;:sc;s: :;. .    .:s;;;;;cs65S6S6SSPYEPHDHEDDEDDDDDDDDDDDDDDDDDDDDDDDDDD
:::. ::  ssss                        ...;..                  :62     .52cc;; ..:    s;s;22ss;;;:.:      s 5sPZZ5EZDHYP5cDNSD      ;c;;scc2; ..:;;:;s;:;;c66ZSS6SSYSZYNDEDEDEDDEDDDDDDDDDDEEDDDDEDDDDEDDD
...  ssc2  ;ss2                      ::::   :                   ;cS6522s;s;sss      ..        ss;s ..     : : 6cZ6PD652c66ZN:s  ..sc25ccscs;;:::::::s2222YSZS66YYYYDZHEDDEDDDDDDDDEDDDDDDDDDDDDDDDDDDDDD
 ::  ..  .:..:s                             ..:                       2c::  :.  66YS:;.:    .     :;.:;::.    : c:2c56PD62ssZNc . ::::;c;;: :sssscccss2ZYY656YYZYYYEPHEDDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
;:;  :;:s  ..                                                             ss..NDPY.:26;:5c;ss;2s2c22ssss56sc..  : 22cs2cZZPYENYSs:;;25cccccccss:s22c6ZS5566YYZYPZZYEPEDDDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
:.:. :; .    .:                         .                                         522c  ZS56scS5Z652255252c2;s    cc666sZSHHPDDNPZs c6ccsssscc2c225555225SSYSSYPPPPHDEDDDEDDDDDDEDDDEDDDDDDDDDDDDDDDDDDD
     :;   .                                                                           s:c:ss.:  : S5;:;:;:c2c225s:: :;s:PSPPYPYY6655522522cscccc2665556YYZS56ZYPZPPEDEEDDDDEEEDDDDDDDDDDDEEDEEDEEDDDDDDD
 :;                                           ..:                                            .    s.s:2s5cs;sc25ss2526s:; EH66s:6PS6652222csc2255552666YSYY6YPYYZEDHDDDDDDDDDDDDDDDDDDDEDDEDDDDEEDEDDDDD
.ss:s :                                        .::;:.:.                                       . . : c:s.ZSZSYYs2PDDD52.:. ; c2;.6Z2c5S6Ss.c222252566SYYYSSSYYZZDDEDDDEEDDDDDDDDDDDDEDEEDDDEDDDDDDDDDDDDD
s;;:; .                                          :6s   :Z55c                                  s.s:. 6sc:2:S5EN6Z:;:.c52S.   YDZY65ZES225csc2225SSSYYS6666YYYYPPNEDDDDDDDDEDDDDDDDDDDDDDDDDDEEEEDEEEEEDDD
  .:s                  ..                        ;S56c :PZHPc6YY52                      ::    : cs; 5;2s5sYS56sS    c6c5: 2;s.262s;:c6556652256SSS62566SSYYYYPPHEDDEDDDDDDDDDDDDDEEDDDDEDDDDDDEDDDDDDDDD
. .    .:                                            .:;2:..;s556666;:                    :.. : . . 2:5s65656Yc65SSScc .  ccc;cc5Y626Sc:256SSS666665666SSZYPPHDEDDDEEEEDDDDDDDDDDDDEEDDEDDDDDDDDDDDDDDDD
:;c  ..:;                                               :. sP2    2c sDP25cc;; ..:     .  ;::.:.;:s.c.5c55556Z;ssc:::;  : s:ss22cc5655c;566SS66222556SYPZZZPPHEEDDDDDDDEDDDDDDDDDDDDEDDEDDEDDEEDDDDDDDDE
:..:s                                                     ;cPS65DZZPPPDP25c2ZPZDc2ss:;..  ;:;:2scs2sY6YSYZ6S;s::s2::ss;;s:c;52252555c;22SZS665555566YPZYYZPEDHEDDDDDDDDDDDDDDDDDDDDDEDDEDDEDDEEEEDEDDDDD
:.:;sc2;s                                                     62HPYY62.;s5DP5556  52:;;ssc.::.cs2s65cc22cc    ;;sc. . :.. ;:656S52s;26ZPY65c25525SYPZYSYZHEHEDDDDDDEEDDDDDDDDDDDDEDEEDDEDDEDDDDPDDDDDDDD
2sc::   .:2                                                   c;ES .YS6Sc222:;SS2c65YY6YSZ5S66c2ss52:;      ;;;::;. s;2c62655222226SYYSS5552526SYZZZYSYEDNEDDDDEEDDDDEEDDEEDDDDDDDDDDDDDEEEDDDDEEEEDDDDE
c :  s;YP:s                                            .;. .:;c:;:ssZ6ss     .;;YYDPZP6P:c :            :.ssssss;;s;cscs226552226SSSSS66522566SZYZYSYZPHDEDDDEDEDDDDDEEDDDDDDEEEDDDDDDDDDDDDDDDEEDEDDDDE
csc    :c  :s.:                                                 .   c; ;56YY6652s;  ss            :.. : csss;;s;s;cscs525552666SSS66662s226YYSYPY6SSPHEHEEDDDDDDDDDDDEEDDDDDDDDDDDDEEEEDDDDEEEEDDDDDDDDD
.. 565Y    2S..                                                   2cS2 .:.   .            s;. :.;.s;:.cs2cs;ccs:526565SS6555SSSY522222526SYYYYYYYSPEEHEDDEEDDDDEEDDDDEEDDDDDDDPDDEDDDDDEEEEDDDDEEDDDDDDE
;62PD ; :5S                                                         ..::.               .   . . ;:ssssccccs;cs;:2ccs22555566SS65555565SYZZY66566ZDENEDDDDDDDDDDDDDDDDDDDDDDDDEEEEDDDDDDDDDEDDDDDDDDDDEDE
D62YYPNSP2S.s:;                                                           .:  .       . : s;s;sscss;s;:.. : s;555c52S6SSSSSS66526666SYZZS66SYYZZPEDEDDDDDDDEDDDDDDDDDDDDDEEDEEEEEDDEEDDDDDEDEDDEEDDDDDDE
ZYYZP6Z2Ys5s5:;:.s2         .                                   :.:.          . s:  ..s:s:c;s;;:;::.s;sscs2c5c5262S6666SYY6555666666SSS666SYYZPDDEEEDDDDDEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEDDDDD
YZYPP6P2S.;s6  s226     .:.s6                                                   ;::::.:.:::.s;. 2cs;;.2s2s2s526552SYSS6655556666SSSS665266SYPDEHEDDDDDDDDEEDEDDDDDDEEDDEDDDDDDDDDDDEDDDDDDDDDDDEEDDDDDDD
6EPDDYDc56Zc2s26Ps;:s;c::  ;S::                 ..:....                         :.    :.. . :.:.:.s;: ;:s:2c656552YZSS55cc2cSS656SSS6562YYPHHHEEDPDDDDDDDDDDDDDDDDDDDEDDDDDEEEEDDEEEDDDDDDDDEDDDDDDDDDDD
;PYHH66PEc2YD66    sY .    cDcs     .                                               :.. :.s:css;s;;:5c6262652c66SSSS665555S666YYYS2s6SPPDDDEEEDDEEEEDDDDDEEEEDDDDEEEEDDDDEDDDDDDDDDDDDDEDDDDEDEDDDDDDDDD
c2;62HEDEYP6Zss26ZPDNss:.2222  :sccc5:::..                                  ..;;::cs;:. s:s:cscs52s:2;5cYSSSYYSS6655cs55SS526652SZYSPZEHHHHEEEEEDPDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
5662;PYNNHN566Y66YPs;c6226655YEYYc:5Z:           :s:                    :::.s:  :::.. ; ;.: cs;:;.2sS5S6S6YYSZ225556656566666562SSYSPDDDDEEEEDDDDDDDDDDEDDDDDEEDDDDDDDDEEEDDDDDDDDDDDEDDDDEDDDDDDDDDDDDD
22s5c2s52YYDDDESS25:.5Y;.26YPZP55;:.:.:       .  .s:                ::;;::  :.::  . ; 5c5c2s22;:62S6S6S6ZZYY6Sss22225266SSS6YSYSZYEHHNEDDEDPDHDPDEDDDPDEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEDDDDEDDDDEDDDDDDDD
22sS6652s62DPEDPDS6ZZPDYZYY625Y562c: .:::     :.                .         . 62:;..: 2;62; Z6ZYS5ZYYY66YY66ccSYYZYZSSYSYSSSYSYSYYEHNNHDEEDEP6PEDPDHDDDPDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDDDDDDD
:s;cc2s625s; ZPEHEDEDZZZP62SP65ccc2256Ss ..:;. :;.   .;c6s      :.             :;:; 62s:P5EZccZYPZSZ2666565666SY6S2c2sSYS6S6ZPNNNNZ5S5PEDEP6ZPZZDHHHEDDDDDDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDDDDDDD
;S6csc;5cS6S66266DDEEHHHHEHYSs:c552ssc5s s5cs:     ;Z2    .:;2DS2s.;YSY5 .65ZPs2  P652c;YcPYEEY6DDYP6Y66SYSS65652c55YSYSYYHNNNHE622sYYENEHDYDNEDPZDEDDDPDEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDDDDDDD
 ;.;s. c;52222s2sc;6SYSDEHHEENNDYPDDHYSS66655c:;:c6s   ;2s ..   25PY22ZYZZNHc6:c2;DYYYYSY2HD66DDPDYP6YPD66226566S6ZYYSPDNNHN5cs;25S6PZDHPZPPDDPZZZZPDEEEDDDDDDDDDDDDDDDDDDDDDDDEDDDDDDDDDEDDEDDEDDDDDDDD
 s:::ssc:ss;:s;55652c2c;.ss6SZPPPHNHNSccs26cs;:;ss2c;scss; sYYZYY652 .;sYSPPSPscZ6ZSS6PYY6DPYYPPDH6YYZ6S6666SSS6S6YYHNNNZY;;;;25655cPDDHPZZZPPPPDDDDDEDEDDDDDDDDDDDDDDDDDDDDDDDEDDDDDDDDDEDEEDDEEDDDDEDE
 2ccc..:.22::. :.;;2c556552cs262cs;s26SPDZSZDDPPPYSSYS65s5SYYYZYYSSS6SS6ZYDD26scPYY6YSEEPYEDZDPEPH66PP22SSPZ65SSNNNNZZss:;sc6SS665Y6PDPDPPPPDEDEDPPDDEEEEEDDDDDEDDDEDEDEDEEDDDDDDDDDDDDDDEDEDDDDDEEDDDDD
   ;;:;: :.2255s;;;;:ss226SS62cc2csssc26ZS555YDENHHHNHHEPZS622scZYDDEEDDEPYY6SS665DPNHDDDDHNENZD.;22SSSS2s66NNNNPPcc;s:.c2666252SSPPDDPDEEEEEEDZPZPPPZPPDHEEEEDDDPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
;        . . :;ssccs:: sss;c255YYYY62cs:.:ssssscc226PZZPZPHDYZZZDZ56YS55s2YYPPEDNHPPDDPPDDPEc6;c5SSS2sSSNNNNZZ:: .s2ss5566655266YYZYDHEHDPDHEEPYYSPDDPPPPEDDDDDDDEDDDDDDDDDEDEEEEDDDDDDDDDDDDDDEEPDDDEED
 :: ..:  ..::  .. .::cs2c;.::::. ;s5SYSYZYYSS52c;2SSPZYYSYEDHHEEEEHHHHHHPDHEEEHEEEDEZZ66YY2626ZZDESZHHNNPP;s .:;22666565525266S6YYPZDHPPZYDEDEDEDPPZPPPPPDDDDEDDDDDEEEEDDDDDDDDDDDDDDDDDDDDDDDDEDEEDDDDD
 ..    ..  ....::      ;;::scccccs:::;:s22c56SYS5666YS6666YYPYSSZZPPZYZPDDHESSPZPPSYSYYYYZZPDDHHDEYZ56.. ::sc25552s;ss222c5265SSY6ZYENDDZSYZPPDEEDPZPPPDDEDDDEDDDZPDDEDEEEEEDDDDDDDEEDDDEDDDDDDDDEEDEDDD
   ::..           ..           .:c2565c25csssscc2ccc;c6565652566S625YYZYSYYZZZDDYPZPPPPDZP6S55;s::;s;c;s2c6656cs;:s;2c65656666SSZYDEEHPZPZDHEHDZZPPPPZZPPPPDDEEEDPPPPDDDDDDEEEEEDDDDDEEEDDDDDEEEDDDDDDDD
     ......                            .;c556666S652;s5566SSYYSSPZZPZZPZYY55S6SS56;s.:;s:;.:::  ::22;sccs;ss:;  s;656562S6S66665YYPDZZYSPDEHDDDDPZY6YYZPZPPDDDDEDDDPPDPPPEDPPDDEEHHHEDDDDEEEEDDDDDDDDDDD
          .:;                       .               ::;:::::::::ss::  :.  ::::;;;s;s;;;;.:::cc6655;s::::;.s;ss55S55c222c55666565YYDHHNEDEDDDZYPDEHDPDEEEEEDDDDDHEEEZPDDPPPPDDPPYYYPEENHHEDDDDDDDDDDDDDDD
                                    ..:. :;;:::;ssss;;cs;:::ssssss:ssscc;;;;..;;:;:;.:;;sc;;;:s;.:  cs::s;526565222c65666565YSS5PPENDPZYYYZPZYYSZZDHDPPYZPDDDPDDDEDPDPDPPDDDDEDDDZZc266HENHHEEEDDDDDDDDD
   .                                            .:;::...:;cscccsss;sssss;;;;;sccscc2ss;:;;.:  ;:::;:s:s:52222c2c222c2266526265Y6DHEEPZPPDPDDEHP5SYPEDPPYYSYDPPPDDDDEEPPDDDDPPPDEEDEPPSSSSYYEDNHHEDDEEDDD
                                                      . .:s;::::.;cs;sss;s22ss;:..    ..;:sss;ss;;c;522s52ccs;cs2c6665525c65Y6PPHNZSZZPPDDPYYZZYPPDHEEEEDZPZZPPDDEDHEPDDDPPDDDPDPDDEHEHYZ6SYSZYHDNHEDDDD
                                                 .;:.:ss2css;s52sssss;....      ..::;::::::.:.;:s;c;;:sscscs52655252666665ZSZ6PDPDS5ZPPPYYYZYZPZZZZPPPPPPZPYZPPPPDPEEEEDDPPPPPPDDDDPPDEEHPD55ZY2cDPHENHE
                                           :ssc; :s;s;..  ..          ::;;..::ss::;:;;::..:.2csss;2ccscssss;2s522c5565S6Y6Y6EEDEYYYYZYPDEHHNEPZSZDPPZZZZZZPPPDPPPPPEDEEDDZPPPPDPPPPDDPPPDDEPDDDPDSS22HDN
       :::.                                    .:::......     ::::::;:;:::::::::..;;ss;;s;s:;:;:;:cscsss2c222c522c2c2c2c65DPNNHHDPPZEEEDPZPDPPPYZZZPPZPDPYZZZZZDPDPDDEEDDPPPPPPPPDPDDDDDDPDEEDDYPSZSY: D
           ..                                       ..::;;:;;;::::..::........:.::::... :.s;sss;cscscss;s;2c2c2c656665S6PENNNDPPZPZYY6ZDDHEEPYZYZZPDZYYZZYZYZPPPPDPDPDDEEZPPPDPZPZZDPPPPPPPPPDEDEPEZDPPY
             ....                    ..:s;;. .;:.::::::;sss;.:..;;::;;..::::::::::....ss;:;:s;s;2ss;cscs2c2c525265SSS5PDSD  PDEHPZDPDZDEDEDDPYZZPPZZPPPDPYYYYZZPPDPDPDDEEDDPPDDZPZZDPZZPPDDDPDDDDDEZD5SY
                     ....        ..:::::;:::;;s;:;;;:: . .::            . . :.::::;:;:;;::;::.:.:.:.s;2c522c2c66652c5cZD2P    SEPPS5DEHHDEDDPZZZZZZPPPPDDPPSYSYZZPZPZPPEEEDPPPPZPPPDDPPDPDDDDDDPPPPDEDH6
                 :s      ..  ::. ..::     ..:. .:.:... .      ....::..  . . ;:s;;;;;;:::: c;cccss;5252cscs2c52655265ZYPDPNEE6:56ZEZYPPDHDPPPYSYPZYZPPPPPPDPYZYYZZZZPPDPPPEEEEPDPDPPDDDDDDDDPPDDDDPPDDZPH
           ..               .  .:;;:..    ...:::.....:.:::::;;;:    ....;;cs;:::::;::::.s:2sssccs;2c;:2c526265525cS6ZYPDYPNNNNDSDEDDZSYZYZPDPPZZYSYZZDPPPPZYZYYZZPZDPDPDPDDEDPDPDPDZZZZPPDPPPDPPPPPPPPPD
                         ..;;. ::::::ssccss:. .::;;;ss;:::   ..:::..::;::::.  s;;;s;sss;2s2c2cccs;c;s:s;s;s;cs65YSZYYYENDN  SSDEZYPEDPDEPDPZPPPZPPPDPZZPZPPPPSYYZDPDPPPDPEDDDDDPPPPPDPPPPPPPPPPPPPPPPDDP
                             :;::         .:;:.  .;:.   :. :;;ss;;.....    .s:;:    . . .     . . : 2s2c66YYPZPZZYPDDDYS:s    SEDDZYPPDHZYYYPDPYZPPPZZPEDEDPPZZYZYYZYDPDDPPEDDDPDPPPDZPPPDDPPPPDDPPPPPPP
ZYY22.:                                                                             . . s:522cY6PZDPHEEDEDDPDPDDDPPDPHNNNNNNYsSYYPY6ZZPEPDDDPYZPPPZYZPPDPPZZPZZSYYYZYDPPPPPDDDDDDPDPDPPZZPPDDPPDDPDPPZZP
ENNNNNNNNNNNNNNNNNNNNHHZY65s;scc225css;;s::     ::::.:s;::;sccc266666SPPEDPPEEHENNNNNNNNNNNNHHNHEEEDPPPPPPPPDDPZSZNNDZ  YD6YSYDEZYYYZZDHPZZYYYZPPPPPPDPPPPPDPZZYZPPPPHDPPPPPPEDEEPDPPDDPPPZPPPPPZDDPDPDP
YZZZYZZZZPPPDPPEEDEEEEHNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHHNNNNHEDDDPPPZZPZZYPPPPZZPPZZDDZPYZZZSS66NN      PHENPYPPDDDPPPDEY6SSZPPPZYZPPPZYZPPPPPZYYYY66SSDPDDDPDPEEPDPDPDPPPPPPPPDPDDPDPPD
YYYYYYYSSYYZZYYYYZZZZZZZZZYYYYZYYSSYZZZZYYYYYZPZYS6SYYYYYYYYZYYYYYYYYYZZYYZZZZPPYYYYYYZZPZPZZZZZZZYZYYZYPPYZYSPH2N  DDNNNPPESSYYZYDHDDS566ZDPZZYZPPDPPPZZZZZZDPZZSYZZZYPZPPPPEDEEDEPDPDDDPPPPPZPZPPZPPPD
YYYYZYZYYYYZZYYYYYZZYYYYYYYZPYYYYYSYYYYYYZYYYYSYZZZZYYYZPPPZYYYYYYZYZYYYYYYYYYYYYYPZZZZYPZZYZZYYPPYZYYZZPPYZS6HN    NNNEEPDHPPPZPPPPPPYYPPPDPYZZPPPPZYZPPYZZPDPPZSYYYYYDPDPDPPPDDEEPPZPPPZPPPPPPPDDPPPPD
YYYZZZZYYZYZZYZZZYYYYZYZZYYYZZZZYZPZZZZZYYYYZYYYZZPZYYYYYZZZZZYYZZYZZZZZYYYYYYZZPZZZYYYYZYPZZPYYPZPPPPYYSYYZYSPNsYYE  : HNYYSSSSYZDDDDDPPDZYYZZPPPZZZZZPPPPZZPPZZYYSSYYZYYYDPDPDDDDPDPDPPPPPPPPPPDDPPPPP
ZZYZYZZZZZZZZYYYYYYYYYYZZYYYYYZZYYYYZZPZYYZZZZZZYYSYPPPZSSYYZYYYYYYSSSYYZZZZZZYYZYYYYZZZZYDPPDYYZZYYYYPPZPYYZZPHNNPD    NN6666SS652cSZPPZZYSZPPDDDPPPZZZZZZZZPPPPYZYPPPPZDPDPPPPPDPDPPPDDDDPPPPPPPPZZPPP
YSSYYSYYYYYYYYYZZZZZZYYYYYYZZYYYYZZZZSSSSYYYYYYYZZSYYYSYSSYYZZYZZZZZZZDPZYYYZYPPZZZZZZYYYYYYSSSSPZZPPPZZZPYY6SSD;;NNNN  6YZDYSPDEHEDDDPZZYZZPDPPPPPPPZPPPZPPPPPDPZZ6YSYDPDPDDDPPPPPHEDDDDPPZPPDPPPPPPPPD
ZZYPPZZYYYZYYYZZZZZZZYYYYYYZZZYZYZZZZZYZZYYYYYZYSSYYZYYYYYPZZZSYYYZYYYSSYYZZSSYYSYYYYYYYYYYYYYZZPPYZSYYYYYS6EN    . NNE5HHPDDDPZY6YZZZZZZZPPPPPZZZZZZZZPZZZZZYZDPPP6Y6SZYZYPZPPPPDPEDPDPPDDPDZPZZPPZPPZD
ZSSYYYZZZZZYYYYYYYYYZYYZZYSYYYYYYYYYSSSYYYSSSYYYYYYYYYYYYYYYYYSYZYZYYYYYYYYZSSZYSYSSYYZYYYYYZYYZSYSYSYSSSSSSZHsY6D    HNEDYYYYS6YYDDZZZYZZPPPPPPPPPPZZZZZZZPPPPDDPDPPSS66ZYDPDPDPDPEEPDPPPPPDZPPPDPPPPZP
YYYYYYYYYYYZYZZYSYYYYYSYYSSYZYYYYYYYYYYZZZYYZZYZPZYYYYPZZYYYYYSSZYSYYYZYSSYSSSZZYYYZYYZYZZYYZZZZSYYZPPZZPPPNNNNN:;  : HNYY66S6YPZYZZZPZYPDPPPZPPZYYYZPPZZZZPZYZPPPPZPYYSYZYDPDPDPPPEDEEPPPPPDPPPPDPPPPPP
YZPYYSSSSSSSSYYYSYYYYYYYYZZYYYYYYZPZZYYYYYYYYYYYYYYYZZZYSYYYSYYYZZSSYSSYYYZZZZYYZZYYSSSSZZZZZZPPDDYYZZPPZYSN  6sNNHNs ZPSYSSYSZPZZZYPDPPPZZPZZZPPDPPZPPPPPPPPZZDPZZYZYZSYZYZYDPDPPPDPDDDDPDPPZPPPPPPPPPP
YSSYYYYYYYYYYYYYYYYYYZZYYSSSSYYYSSSYYSSSSSSSSYYYYZPZSSYYZZZYYZZZYZZZZZZZZZZZZZZZZZPPDDZPZZYZYYPPYYDDYZ656SNN    NNNNY6PPYZYSPDPPZZZYPPZYYSYYZPZYZYZPPPPDPZYSYYZPPPPZPSY6SYSPZDPDPDPPPPPDDPDPDPDPPPPPPPPP
PPPDDDDPZPPPPZYZZZZZZZZYYZZZZZZZZZZZZZZZPPPZZYYYPZYYYYPZYYYZPPZZYYZZZZDPYZYZZZYZYYYYZZZPYZSSYY6652SS5666HNsY6DZ N2DNEHZSYZYYPPZYYZZPPDPZPDPPPDPYYYYZYYZZZZPZPZPDPDDPPZPYYSSPZZYPZDDPPDPDDPDPPPDDDPPPPDDP
SYYYYSSYYZZYZYYYYYYYYZYPPPPZYZZZPZZPPPPZYYYYPZPZYYSYZZPZSSSSYYSYSYSS56YS6SSSSS66SSSS56YY6S552265ZYSY66DNZN      NZHNPPYSPDPZYYYYZPZYYZYYZYZZZZZYZPPPZYYZZZZZZZPPPPPYZYZ6S66YYPPPZPPPPDPDDPDPDPDPPPPPPPPP
YSSSSYYYYYYSSSSYYYYSS66SSYYS6SSYZYYSSSSS66SSYYSS6SYYSSSSSSYYYYYYZZYYSSYYYYSSSSYYYYYYYYSS6666YYS6ZYSSYYZN  ;:  Z;NNPPYYYZZYYZYYYYYYYZZZYYYYYPZZZYPDPPZZZPPPPZZZZZZDDPDZPYZSYYSPYZZDPDDDDEDPDPPPPZPPPPPPPD
ZYZYSZYYYYZSSYSYZZPYZSSYSZPZYYSYYYZYSYYYYZZZZYYYYZZZYYSSSSYYYYYYSSSYYZYZZYSSSSZZYZYY6666YYZZYYPPPPZZPD5N  ::NNNNHDYZYYYZS6YYZPPPZYPPZZYYYYZZPPPPZYYYYZZZZZZYZYZYZDPZPYZYYSSSYDPPZZZPZDPEDDDPDPDDDZPZPPPD
PYZYYZZYYYZYYYYYSYZYYYSYYYYYYYSYYYYYYZZYZYSSSSYSYYSYYYZZZZYYYYYYYYYYZYSYYYYYYYSSYYSSSSYYZYZZYYPPYYPZDDYN ;NN  D5NNYSYZZZYSZZYYYYYYYYZPPPZPZZZZZZZPZZZZZZZPPZZZZZZDPYYSYSY6SSSYYPZDPPZDPDPEEPDZPDDDDPPPPP
YSSYYSSYYSSYYYYYSYYYYYYYYYSYYZZZYYYYYSSSSSYYYZZYYYSSYYYYSYYYYYYYZYZZYZYYYYYYZZPZZZYYPPDDPPYYPZYYPPYYYPNNNN    DcPPS6YYZYZZPPYYYYZPZZZZZZZPZZZZZZZPPPPZZYYZZZZYZZZDPPPZPZZYZZZYSY6DPDDDPDDEEDDPDZPPPDDPPD
YYYYYYYYZYYZZYYYYYZYYYYYYZZYYYZYZYYYYYYYYYYZYYYYYYSYYYYYYYZZZZYYZZYYYYZZZZYZYYZZDPZZYZZZPPZZZZPZPZPPHN  SYNN  ESZYYZYYYYZPZYZZPPZZZPZZZYZZZPPPZZZZZPPZPPPPPZZPPZZPPPPPPYZSYSYZZPYDPDPDPDPPPPPDDPPPPPPDDP
YZYZZYYZYYYYSZZYZYSZZZZYYYZYYYSYYYYYYYYYZZPZYYSYYYYYYYYYYYZYYYZZZZYYYYYYYYYZSYYYZZYYYY66SSZYYYYYYSHNsH    EYHPPYZYZYZZYYYYYYYSYZZYZPPPPZPZZZYYZZPPPZZZZZYYZYYZZZPPPPPPPZPYY6SYYPZDPPZPPDPDPDPDDPDZPPPPPP
YYYYYYYZZYYSYYSSYS6YZYZYYYYYZYYZZZZYSSSYZYYS6SSYSYZZPPZZYYZZZYSSZZPZ6SYYYYZZYYYYYYZZYZYYYSYYPPYYYSZE 6    ; NNS6SSYYPZZYYYYYYYZZPPPPZZZZZPPPZZYYZPPPPPPPPZZZZYYYZDPPZZZZPSYSYZYS6ZYZYZYPPPPDPDDDDPDZZPPP
SYYYYZZYYYYZZYYZZZZZZYSYSYZZZYSYYYYYZZZZZZZZZZZZZZZZZZZPPPPZSYYYYYZZYYZZZZZZZZZYYYSYYYZZPZDDYYZYZHNNNNNN6Y2 NHYZYYSSYYZZZZPPDDPYZYZZZZPPPZZZZPPPZYYYYYYYYYYYYZZZZDPPPDDDDYZ6SZZPZPZPZPZPPPZPZDPDDPDPDPPP
YZZZPYYYYYZZZYYYYZYZPZZZZZZYZYYSSYZZZYYYSYYYZYSYYYYZZZZYZYYYSYPPSS66YYSYYYSSYYYYPPZZYYYYZZYYSSZYHN  S NN6Z2 NESYYYYYYYYYYYZYZZZZZPPPZZYYYZZZZZYYZZZZYYYYYYYZZZZYZPZPPPPYZ6YSS66S6PYPZDPDPPPPPPPDPDDDDPPP
YPZYZSSYYZZYYYYYYYYYYYYYYYYYZZZZZYYYYZPPPYYYYYZZYYYYYSSSYYZZYYZY5SZZDPZZZPZZZZZZPZYZYZZZZZYY66ZD6N    YS .  DPSYZZYYYYYYYYZYZZZZYYZPZPZYZZZZZZZZZZYYZZZPPPZZZZZYZDPPPPPYPYZYY6SYSPZYSPZDPDDPPPPDPPPPPPPP
YSSSSSSZZYYYYYYYYZZYYYYZYZZYYYYYYZPZYYYYZYYYZYYYYZZZZZPZYZZZYZPZSSSSZZZZZYZZZZYZYYYZYYZZYYZZY6DN 65ZNNH5NNNNY6ZPSSYYYYYSZZZYZZZYYYYYZPZZZYZPZYYYZZZZZZZYZZZPPZZSYPZDPPPZPYZSYSSYSZYZYPZDPDDZPPZPZDPPPDDP
ZYZZZYYZZYYZYZPZZYYYYYZYYYYYZZZYYYYYYSSYYYYYYYYYYZZZZZPPZZPPPPYZDDZYYYYYPZYYZZYYYYSSSSYSYY66DDNN:YPP  ; NNZDZZZZYSZPZZYYZZYYZZZZZZZZZZZZZZZPZZZYZZZPZYZZPPPYYYZZZPZDPPPZPSYSYSSSSPYPZPZZZPPPPPZDPDDPPDDP
YYYYYSSYZSSZYZZYYYYSSSSYYYYZZYYS6YYYZZYYZYYYYYYYYYSYPZYYYZPZSYZZYYZZPPYYZYYYYYZYYYYYSYYSZYZPDN.5      P2NN56SYSSZZZZYYSSYYYYPZZPZPZPZYYYZPZPZZZYZZZYZZZZZYYZZZZYZZZDPPPZPYZ6YYYZYZYPZPPZZPPPPDPPPDDPPDDP
SYYYYYYZPYYYYYYSSZPZZZYPPYYYZZZZYZZYYYSYZZPZYZZPPPPPPZYYZYYYYYYYYYSYZZYY6SYYYYZZYYZZYZSSPZZN;Y. SZ  N2NNPDSYYSZZYYYYYYYYYYYYYYYYZZZZYYYYYYYZYYYYYYYYZZZZZYZPZZZZZZZPPPPPPPP566SSSZYDZPZZYDPPPPPPPPPPPDPP
ZZZPPZPYYSSYYYZYSZZYYYYYYYZZPZZYYZZPPPPPZZZYYYYYYYYYSYZZDPYZPYSYZYSSYYZZSYZZZYZZYYZZZZSSZZPN    NNNNNYNNSYZZPZPPYYYYZZZPPPZZZYZZZPZZZZZYZZYYZPPPPPYYYYYZZZZZZZZPZZZDPDDZPZPZPZPYYZYPYZZZYPPPPPPPPPPPPPZP
YYYYSZZYYYZZYYZYYZYZZYYYYYYYZYYZZZZYYYYYYYYYZYSYYZPZYZPYYYYYZZYZYYZZPZZZZYYYZZZZYYYYZZZZYZSH;5NN;c  NPPD6SYYZPYYYYZYPZZYYYYZYYYYYYYYZZZZZPZZZYYYYPPPPZZYZPZYYZZZZZZDPPPZPPPYZ6666S6YYZZPZPZZZZZPZPPDPPPD
YZZZYPPYYYYYYYZYYYYZPYYZZZZYYYYZZZPYYYZYYYYZPZYYYYZZYZZZZZPZYYYYYYYYZZZYYYYYYYYZYYYYZZYYYZ5YEN6D    NEYYZPZZPPYYZYYYSSYZYYYZYYYYYYS6SSSSZZZZYYYYYYYYYYYYZZZYYYYZZPZDPPPZZPPZP6YYYYSZYPZPPPPZPZZPPPPPPDPD
YSSS6ZZZZPPYYYYYYYYZZZZZZZYYYYYYYZZYYZZZZYYZZZYZPZZZYYYYZYYYSYYYZZYYSSSSZYYYZZZZYYPPYZYYYYDN:Y  D2NNS6SSYSYYYZSSZZPPYYZZZZZYYYZZZZPPPPZYYZZPPPPPZZYYZPPPZYYYYZYYZZZPPPPZPZPDDDDDDDPPPDPDPDPDDPPZPYYZYPZP
ZYYSSYYS6YYZZZZZZYYS6ZZYYYSZPZZY6SYYZZZYYZZYZZZZZYYYZZZZZZZZZZZZPPZZYYYZPPYYYYZZYYYY66ZP6SYE Y  E NN6ZZZZZPPSSYYYSYYZZYYYYPPZZYYYSZPZZPPZZYYYYYYYZZPZYYYYZPPPPZYYYYPPPPZPZZYZYZSSEDHDZZZYPZPPPPPPZPPPDPP
ZZZZZYYYYSSSSYYZPZZZZYYYYZZZPYYYYZZZPYYYSYZZPZYZPZZZYZPZYYYYZY6SSSYYZZPPYYYYYYZZYYZZYYPDZPZH5N  N2NH5YYYYYSSYYYYYYZYYYYYZYYYZZPPZYYYYZYSYZYYYZZZZZZPPPPPZYYYYYYZZYZDPDPZZZZYZSS25S6PZZZDPDPPPPZPPPPPPPPP
ZZYZZZZZPPPPPZZZYZZZZYYSSYYZZYYYYZZZPPPPZZZZZZZYYYYYYSYYYSSYZYSYYYYYYYZYYYPPZZYYSSZYYPNN6SNN 6  N2HE5SZZYYYYZPYYSSZPZZSSZZYYYYYYYYZZZZZYZZZYZZZYYYZZYYYSYYYZZYYPZZZPPDDPPZPZPYZSYS6ZSZYZYPZPPPPDDPPZZZZP
YYYZZZZYZYYYZYYYSYYYYZZZZYSYYYYYYYYSSSSYZYZYYYYYYYZYZYYYYZPZZZZPDPYYZYYYYYZYYYYYYSZDNNcZ  ZY :: NSZZYZYYYYZZYYYYYYYSYYYSZPZZYYYYZZZZYYYZZZYYYYYYYYYYYYYSYZZZZYYPPZZPZPPPPPPZZ6YYY66ZSPYZYZYPZPPZZPPDDPPP
YZZZZYYYYYYSSSSYYYYYYZZZZZZZZYYYYPDZZYSYZYYSSYYYZYYYYZYYYYYYYYSSYYSYYZDPYYYYZZYYYYNN    s:  ; NNHESSSYYYYYZZSSSSYYYYYYYYYYYSZZYYZPYYYYYZYSZPPDPPZYZZYZZZZZZYYYYZZZZPPEDPPZZYZSYSY56YSPYDZPZPZPZPPPPPPPPP
ZYYYYZZPPPPZPZZZZZZZZZZYZYSYYYZYYYYYYZZZYYZZZZYYZZZYYYSYSSYZPZYYSYYYSSSYZZYYSSSSEE6D 2NNNNNH6 NE5SYYYYYYS6YYZZPZYYZPZZZZZZZZPPZZPPZZYYZZYYYYSSYYZZZYZYZZZYYYZPPZZYYPZDPPPPPZPPDPD6S6562ZYPZZZPZPPPPZZPZP
ZYYSSYSYYZYYYYYYYZZZZYZYYYSYZZZYSYYSSYZS6SSYZYYYYYZYSYYYYYZYSYYYYYYYPZYYSYZZYYYSDNsEPE22  P.NNZD6YSSSSYYYYYYSSYYYYYYZZZZZPYZYYYZYYYPZYZZZZZZZZZZZZYYZZZZYYZZZPZZZYYZYYYYYYZYYSS56SYPPNEEPPZPZZZPPSYYYPZD
YYYZZYYYYYZYZYYYSYYYZYYYZZZZZYZYYZZZYZZZZYYYYYZZYSSSYYYSSYYYSYYYYYSSYYZYYYYYSYPENN          NN6P6SYYYYYYYYZZSSYSYYYSYSYYYYYZYYYYYYYYYYZZZZZZZZZZYYZPZZZZZPZZZZZZZZZZZPPZZZPPDYZSY25::ssZYNEHDZZYPYDZPHEE
ZZZYZYYPPPPZZYYZZYYYYYYZZYYYSYZYYYYS6SYYPZZZYYYYZZZZZZPZZZZZYYZZZZYYSYZYYYYYDPSZ  6S6S  . NcNNs6YSPPSSYYSSYYZZPPYYYSYYYYZZZZYYZZPPZYZYZYYYYYYYYYYYZZYYYYYZZYYZZZZPPZZDDPDZPYZYPDHENPP5c.   PYNNNNZDsc  s
YYZSSSSYYYYYYYYZYZZYYYYYYYZYSYZYYYZZZPDPZYSYYYYYYYYYYYZZYYYYYYYYYYPZYYYYZZYYPPSP  NDNNNNDsNNZPSYYSYYZZZZZZZYYYYZSYYYZZS6ZZYYYYYYYZYSYYYYYYYYYZYZZZZPZZZZZZZZZPZZZZYSYDPPPZPZZSS;s:s25HHNNHPS6.s  ;:S6DPE
YYYZPZZYYYZYYYYYYYZYYYYYYYYYYYYYYYYZZYYS6SSSYYYYZYSYYYYYSYYYYSSSYYYYSSYYSSYYZZSD26PZDNS2EcNN2SZZYYYYZYYYYYZZPPZZYYZZZPZZZZPPPPPZZZYYZPPPZYZZZZZZZPZYYYYYYZZYZZZPZYZYYDPPPPDDDYPYP6Ycc: 2sZYNNSZ.:YSPPNHD
YYYYYYYYYYYYYYYZZZZZZZYZZYYZZZZZZZZZZYYYYYYYYYZYYYYYSYYYYYYYZZYYYYYYZZZZYYYSYYSP6YZS    NYDD2666YSZYYYYYZYYYYYZPZZYYYYYZYYYYYSZPPDZYZZZPZZZZYZYYYYYYYYYPZZZYYYYPPDDZZDPDPPPYZYZZD5Y56ZSS562S5ZPNNDD55:;c
ZZZYYZYZZYZZZZZYYYZYYYYYYYYYZYYYYYYYYYYYYYYYSSSYYZPY6SSYZYYYYYYYYYYYZYYYYYZYZZPD5ScSHNNNHP66YZPPZZYYYYYYYYYYYYYYYYYYYYZZZZYYYYYYZZPPPPZZYYYYYPZZYYYSYZZZYYYZZPZZZZZZYDPPPZZPPZPSP2Yc266PZYSPYPYZYPDEHHNZ
SYYSSYYYYYZYYZZZYYYSSSSYZZZZPYYYYZZYYYYYYZPZPZYYYYZYSYYYYYSYYYYYZZZZZZYYSSZYPP6Y26;sDYNN5SYYZYYYYYYYPZPPZZZZZZYYYYZPZZZYYYYYZZZYYYYYZZYYYYYYZPZYZPZZYYYYYZZZZZZZYYYYYDPDPZPPDPP6Y2Sc252Y6YYPYPYPZDPYYZPP
YZZYYYYZZZZYSSSYYZZPPZZZYYYYZYYYYYYSYYYYSYZZZYSSSYYYZZPZYYYYZZZZPZYYSSYYPZYS6S2YHNNH5;EDSZZZPZYYZZPPYYYYYZYYYYYYYYYYYYYYYYZZZZYYZYYYYYZZZPZZYYYYYYYYYZZPZYYYYYZPPPPYYDPPDPPZPZPSP5Y6S66S6S6S5PYPYPPPPZYY
YZYYYZZYYSSYZZZZZYYYYYZZZYYYYYYYSYYZZYYYYYSYYYZPPZZZYYZYYYYYYYSSYYZPZZZZSPNNNNNN    5;HE6SYYYYZZPPZZZZZYPPPPZZPPZZYYYYZPYYYYZZYSYYZZZYZZZPZZYYYYYSYYYZZPZYZPZYYZZZPYYEPPPPPZZYZSZ5Ys2cc655cY5Y6Y6YSYSDZH
YZPYYYYYYYYZYZZZPYYYYYYYYYSYYZZZYYYYZYSZPZSYYYZYSSYYYYYYYZYZPZSSZYSS6SPEHH.;  HE  s HZZYYYZYZZPZYZ66YYZZYZYZYZYYZYPPPPZZZPYYYYYZZZYYYZZZYYYYZPZYZZPPZYYYYZZPPPPPPZZYYDPPPPPPPZPSZ2Y:css:.s:S2Y6S6YSZSDYH
YSSZYPPYZYYZZYYYYYYZYYYYYYYYYYYYYYYZZYYYZYSSSSYYYYYYYYYYZZYYYYSSZZYYYZPS        6;NNZZS6ZYYYYSYYPPZZYSZZZZYYYYYYYYYYYYSSZPZPZYZZZZZYZZZZYSYYYZYYYZZZZYYYYZYYYYYYZZZZZDPPPPPPPYZSZ5Y265552Y56cPSPZYYZYDYE
YYYYYZZYYYYYYYYZYYYYYYYYYYYYYYYYYYYYYYYSSSYZZZYZZYYYYYZYYYSYYYYYYYYZDE6Y2YNNHN    NN26ZZYYZZYYPZSSZPZPZZYYYYZZYYYYYYYYYYYYZZZZZZZYZZZPZYYYYYYYZZZZYYYYYYYZZZZPZYYYYZYDPPPZPZPZPYD5Ys5ssY6DYY6YSZZ66S6ZSY
YZZYYSSYZYYSSYYYYZZZZYYZZPDZZYSSSYYYYYSYYYZYYSSYYYYYSYYYYYSYYZDPYYYYS6 :NENNNNYYZ2HPYZPZZYPPZZPZZZPZYYSYZYPPZZZZYZPZZZZYPZYYYZYYYYYYZZPPPPZZZYYYYZZYYYYZZZYYYZZZZZZZZEPPPZPPPZZ6Y2Ys2csY5S5DPZYYYZZSSYYS
YYYZZZZYZYYZZZZYYYYYYYZZPYYS6YPZZYSYSYYYZYYYYYSSYYPZYYYYYYSSSYZYYZDZ;5SDNESS  NZNN6S56SSYYYYYSYYYYSSPPYYZYZZZZPPYZYSPPZZZZZZYYYZPPPPZZYYZZZPPPZYZPZYYYYZZYYYYZZPZYYYYEDPDPPZZSYZD5Y:scs2sY5Y6ZYYYZZYYYYY
YSSYYZZYYYYZZYYZZYZYYZZYYYZZZYSSSSSYYZPZZY6SYYYYYYYYZZPZZZYYZYYYPEDNNN;.  cs    NH6YZZPPYYSYYYPZPPPPYYYZPZYYYYYYYYYYZZYYYYYZZZZYZZZZZZYYYYYZYYYYYPZYYYYZZZZZZZYZZZZZYEPZPYZZPPPZD5Yc6YSY6S5Y6YYYYSS6SYYY
YZZZZYYYYYYYYYYYYYZZZYYYYYYYZYSYYZPYSYYYYYYYZZZZZYYYYYZYYYYYZYYYPS  s2HH s;sccNHPYYYPPZZYZZZYYYSZYZZZZZYYYYZYYZYZZPPZZZZZZZZZZZYZZZZZZZZZZZZZZZYZZZZZYZZZYZZZZZZZZZZZDDDDPPZZSY6S6Y562cS6ZSDZZZZZYZZZYY6
*/


package com.boxuk.jenkins.jslint;
import hudson.Extension;
import hudson.Launcher;
import hudson.model.AbstractBuild;
import hudson.model.AbstractProject;
import hudson.model.BuildListener;
import hudson.tasks.BuildStepDescriptor;
import hudson.tasks.Builder;
import java.io.IOException;
import org.kohsuke.stapler.DataBoundConstructor;

/**
 * A {@link Builder} for JSLint. Takes parameters to determine filesets to
 * include/exclude and creates output in Checkstyle format.
 *
 * <p>
 * When a build is performed, the
 * {@link #perform(AbstractBuild, Launcher, BuildListener)} method will be
 * invoked.
 * </p>
 *
 * @author Gavin Davies <gavin.davies@boxuk.com>
 * @license MIT License http://www.opensource.org/licenses/MIT
 */
public class JSLintBuilder extends Builder {

    /**
     * Ant file-set pattern to define the files to scan.
     */
    private final String includePattern;

    /**
     * Ant file-set pattern to define the files to exclude from scan.
     */
    private final String excludePattern;

    /**
     * Location to log to - e.g. target/jslint.xml.
     */
    private final String logfile;
    
    /**
     * User entered arguments
     */
    private final String arguments;

    /**
     * Fields in config.jelly must match the parameter names in the
     * "DataBoundConstructor".
     *
     * @param includePattern files to include - apache ant filter
     * @param excludePattern files to exclude - apache ant filter
     * @param logfile xml location to log to
     */
    @DataBoundConstructor
    public JSLintBuilder(
        final String includePattern,
        final String excludePattern,
        final String logfile,
        final String arguments
    ) {
        this.includePattern = includePattern;
        this.excludePattern = excludePattern;
        this.logfile = logfile;
        this.arguments = arguments;
    }

    /**
     * @return The include pattern - apache ant style filter
     */
    public final String getIncludePattern() {
        return includePattern;
    }

    /**
     * @return The exclude pattern - apache ant style filter
     */
    public final String getExcludePattern() {
        return excludePattern;
    }

    /**
     * @return Where to put the XML log
     */
    public final String getLogfile() {
        return logfile;
    }
    
    /**
     * @return User arguments
     */
    public final String getArguments() {
        return arguments;
    }

    /**
     * Perform this JSLint operation.
     *
     * @param build The build
     * @param launcher Launcher
     * @param listener Listener
     * @return True if it worked, else false
     * @throws IOException Can be thrown if can't read files
     * @throws InterruptedException Can be thrown if build interrupted
     */
    @Override
    public final boolean perform(
        final AbstractBuild build,
        final Launcher launcher,
        final BuildListener listener
    ) throws InterruptedException, IOException {

        listener.getLogger().println("[JSLint] Ready");

        // Get a "channel" to the build machine and run the task there
        launcher.getChannel().call(
            new LintRunner(
                build,
                listener,
                includePattern,
                excludePattern,
                logfile,
                arguments
            )
        );

        listener.getLogger().println("[JSLint] Complete");

        return true;
    }

    /**
     * Implementation of an extension point. Descriptor for this class.
     *
     * This builder can be used with all kinds of project types.
     */
    @Extension
    public static final class DescriptorImpl
        extends BuildStepDescriptor<Builder> {

        /**
         * @param aClass Project to check whether this plugin can be used with.
         * @return Whether this descriptor is applicable - always true
         */
        public boolean isApplicable(
            final Class<? extends AbstractProject> aClass
        ) {
            return true;
        }

        /**
         * @return This human readable name is used in the configuration screen.
         */
        public String getDisplayName() {
            return "JSLint";
        }
    }
}
